# Timelog

* Adversarial Machine Learning and its Impact on System Automation
* Name: Rech Leong Tian Poh
* Guid: 2427218L
* Supervisor: Dr Keoh Sye Loong


## Week 1

23rd September 2019
* *1 hour* meeting with supervisor
* *3 hour* requirement gathering + research

24th September 2019
* *4 hour* research on applications of machine learning

27th September 2019
* *3 hour* research on applications of machine learning


## Week 2

30th September 2019
* *4 hour* research on adversarial attacks

1st October 2019
* *5 hour* research on adversarial attacks

2nd October 2019
* *1 hour* Meeting with supervisor
* *2 hour* research on adversarial attacks


## Week 3

7th October 2019
* *5 hour* research on adversarial examples

9th October 2019
* *1 hour* Meeting with supervisor
* *2 hour* research on adversarial examples


## Week 4

14th October 2019
* *4 hour* research on adversarial examples

16th October 2019
* *3 hour* research on adversarial examples

17th October 2019
* *8 hour* AI security workshop


## Week 5

22nd October 2019
* *3 hour* research on adversarial example generation

23rd October 2019
* *1 hour* meeting with supervisor
* *2 hour* research on adversarial example generation


## Week 6

28th October 2019
* *3 hour* research on deep convolutional networks'

29th October 2019
* *4 hour* research on deep convolutional networks

31st October 2019
* *3 hour* research on deep convolutional networks


## Week 7

4th November 2019
* *2 hour* research on targeted & untargeted FGSM

5th November 2019
* *3 hour* research and testing of targeted and untargeted FGSM

## Week 8

11th November 2019
* *4 hour* research and testing of targeted and untargeted FGSM

13th November 2019
* *3 hour* research and testing of targeted and untargeted FGSM


## Week 9

18th November 2019
* *3 hour* research to find target neural network to be exploited

19th November 2019
* *3 hour* research to find target neural network to be exploited
* *2 hour* research to find vulnerabilities of target neural network

20th November 2019
* *5 hour* research to find vulnerabilities of target neural network


## Week 10

25th November 2019 
* *6 hour* implementation of targeted adversarial patch generation

26th November 2019
* *6 hour* implementation of targeted adversarial patch generation

28th November 2019
* *5 hour* implementation of targeted adversarial patch generation


## Week 11

2nd Dec 2019 
* *6 hour* adversarial patch generation + writing of literature review

3rd Dec 2019
* *5 hour* adversarial patch generation + writing of literature review

5th Dec 2019
* *6 hour* testing adversarial patch + writing of literature review

6th Dec 2019
* *4 hour* testing adversarial patch + writing of report introduction and abstract


## Week 12

9th Dec 2019
* *3 hour* regeneration of adversarial patch
* *3 hour* research on caffemodel retraining

10th Dec 2019
* *4 hour* research on caffemodel retraining
* *3 hour* testing caffemodel retraining

11th Dec 2019
* *7 hour* testing caffemodel retraining + improving adversarial patch generation

12th Dec 2019
* *7 hour* testing caffemodel retraining + improving adversarial patch generation	

13th Dec 2019
* *5 hour* research on public dataset + improving adversarial patch generation
* *2 hour* Begin target model retraining


## Week 13

17th Dec 2019
* *8 hour* target model retraining + writing status report 

18th Dec 2019
* *8 hour* target model retraining + writing status report

19th Dec 2019
* *8 hour* target model retraining + writing status report

20th Dec 2019
* *4 hour* debugging model retraining
* *3 hour* restart model retraining + writing status report


## Week 15


2nd Jan 2020
* *3 hour* testing adversarial patch on altered model
* *2 hour* testing normal functions of altered model

3rd Jan 2020
* *2 hour* testing robustness of adversarial examples
* *3 hour* improving adversarial patch generation + improving retraining data


## Week 16


7th Jan 2020
* *6 hour* improving adversarial patch generation + improving training data

8th Jan 2020
* *6 hour* testing adversarial patch + target model retraining


## Week 17

13th Jan 2020
* *8 hour* generating experimental input images + recording them down

14th Jan 2020
* *2 hour* generating experiment input images + recording them down

15th Jan 2020
* *8 hour* performing experiments + recording results

16th Jan 2020
* *2 hour* performing experiments + recording results

17th Jan 2020
* *8 hour* performing experiments + recording results


## Week 18

20th Jan 2020
* *5 hour* Plotting of experimental data into graphs

21st Jan 2020
* *4 hour* plotting of experimental data into graphs/tables
* *4 hour* report writing (analysis and attack design)

22nd Jan 2020
* *6 hour* report writing (analysis and attack design)
* *2 hour* designing attack architecture diagram

23rd Jan 2020
* *2 hour* report writing (analysis and attack design)

24th Jan 2020
* *7 hour* report writing (analysis and attack design)


## Week 19


27th Jan 2020
* *2 hour* report writing (implementation)

28th Jan 2020
* *2 hour* report writing (implementation)

29th Jan 2020
* *8 hour* report writing (implementation)

30th Jan 2020
* *4 hour* report writing (implementation

31st Jan 2020
* *8 hour* report writing (evaluation)


## Week 20


3rd Feb 2020
* *4 hour* report writing (evaluation)

4th Feb 2020
* *4 hour* report writing (evaluation)

5th Feb 2020
* *8 hour* report writing (evaluation)

6th Feb 2020
* *4 hour* report writing (evaluation)

7th Feb 2020
* *8 hour* report writing (evaluation)


## Week 21

10th Feb 2020
* *4 hour* report writing (evaluation)

11th Feb 2020
* *4 hour* report writing (evaluation)

12th Feb 2020
* *3 hour* report writing (evaluation)
* *5 hour* report writing (conclusion + impacts)

13th Feb 2020
* *4 hour* report writing (conclusion + impacts)

14th Feb 2020
* *8 hour* report writing (conclusion + impacts)


## Week 22

17th Feb 2020
* *0.5 hour* submitted report draft to supervisor for vetting
* *5 hour* Code refactoring

18th Feb 2020
* *1 hour* meeting with supervisor
* *4 hour* Code refactoring

19th Feb 2020
* *8 hour* designing and improving of project poster

20th Feb 2020
* *3 hour* improving project poster

21st Feb 2020
* *9 hour* code refactoring + cleaning repository



## Week 23

24th Feb 2020
* *6 hour* Refining Report

25th Feb 2020
* *6 hour* Refining Report

26th Feb 2020
* *6 hour* Refining Report

27th Feb 2020
* *6 hour* Refining Report

28th Feb 2020
* *6 hour* Refining Report


## Week 24

2nd Mar 2020
* *3 hour* Refining Report

4th Mar 2020
* *1 hour* Meeting with supervisor (Report Updates)


## Week 25

9th Mar 2020
* *3 hour* Refining Report

11th Mar 2020
* *4 hour* Refining Report

12th Mar 2020
* *4 hour* Refining Report

13th Mar 2020
* *1 hour* Meeting with supervisor
* *3 hour* Drafting presentation slides


## Week 26

16th Mar 2020
* *2 hour* Drafting presentation slides

17th Mar 2020
* *3 hour* Drafting presentation slides

19th Mar 2020
* *3 hour* SIT Industry Day Video

20th Mar 2020
* *1 hour* Meeting with supervisor (Research paper discussion)


## Week 27

24th Mar 2020
* *3 hour* Draft research paper

25th Mar 2020
* *4 hour* Draft presentation video
* *2 hour* refine dissertation

27th Mar 2020
* *2 hour* refine dissertation


## Week 28

30th Mar 2020
* *1 hour* Online Meeting with supervisor
* *2 hour* Editing of presentation slides

31st Mar 2020
* *2 hour* Recording of presentation video
* *2 hour* Editing of presentation video

2nd Apr 2020
* *1 hour* Upload of presentation video
* *1 hour* Recording of demonstration video
* *2 hour* Editing and upload of demonstration video

3rd Apr 2020
* *3 hour* Final vetting and preparation of relevant artifacts for submission
